version: '3.9'
services:
  top-api.mongo:
    image: top-api:latest
    restart: always
    container_name: top-api.mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017

    volumes:
      - ./.env/opt/app/.env
